title:            Learning and Reasoning
description:      The Learning and reasoning group at Vrije Universiteit Amsterdam

defaults:
  -
    scope:
        path: ""
    values:
        article: true
        maps: false
        front: false